dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -q errbot pytest pytest-pep8 --use-wheel
  - pip install -q coverage coveralls --use-wheel
script:
  - coverage run --source typetalk -m py.test --pep8
after_success:
  - coveralls
notifications:
  email: false
